spring:
  config:
    activate:
      on-profile:
      - prod

appinfo:
  build:
    version: s1:1.0

custom-config:
  name: My Prod Custom Config
  object-data: 
    prop1: "Prod Value of Prop 1"
    prop2: "Prod Value of Prop 2"
    prop3: "Prod Value of Prop 3"
  list-data:
    - "Prod Value 1"
    - "Prod Value 2"
    - "Prod Value 3"
