spring:
  application:
    name: cloudfunc
  cloud:
    function:
      definition: processData|print
    stream:
      bindings:
        processDataprint-in-0:
          destination: student-data
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: localhost
    connection-timeout: 10s
