spring:
  application:
    name: cloudfunc
  cloud:
    function:
      definition: processData|print
    # stream:
    #   bindings:
    #     processDataprint-in-0:
    #       destination: student-data
    #   kafka:
    #     binder:
    #       brokers:
    #         - localhost:9092

